# Generated by Django 2.2 on 2020-05-02 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('USD', 'US dollar (USD)'), ('JPY', 'Japanese yen (JPY)'), ('BGN', 'Bulgarian lev (BGN)'), ('CZK', 'Czech koruna (CZK)'), ('DKK', 'Danish krone (DKK)'), ('EEK', 'Estonian kroon (EEK)'), ('GBP', 'Pound sterling (GBP)'), ('HUF', 'Hungarian forint (HUF)'), ('PLN', 'Polish zloty (PLN)'), ('RON', 'Romanian leu (RON)'), ('SEK', 'Swedish krona (SEK)'), ('CHF', 'Swiss franc (CHF)'), ('ISK', 'Icelandic krona (ISK)'), ('NOK', 'Norwegian krone (NOK)'), ('HRK', 'Croatian kuna (HRK)'), ('RUB', 'Russian rouble (RUB)'), ('TRY', 'Turkish lira (TRY)'), ('AUD', 'Australian dollar (AUD)'), ('BRL', 'Brasilian real (BRL)'), ('CAD', 'Canadian dollar (CAD)'), ('CNY', 'Chinese yuan renminbi (CNY)'), ('HKD', 'Hong Kong dollar (HKD)'), ('IDR', 'Indonesian rupiah (IDR)'), ('INR', 'Indian rupee (INR)'), ('KRW', 'South Korean won (KRW)'), ('MXN', 'Mexican peso (MXN)'), ('MYR', 'Malaysian ringgit (MYR)'), ('NZD', 'New Zealand dollar (NZD)'), ('PHP', 'Philippine peso (PHP)'), ('SGD', 'Singapore dollar (SGD)'), ('THB', 'Thai baht (THB)'), ('ZAR', 'South African rand (ZAR)')], max_length=3)),
                ('rate', models.FloatField(max_length=10)),
                ('from_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.Currency')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCurrency',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(choices=[('USD', 'US dollar (USD)'), ('JPY', 'Japanese yen (JPY)'), ('BGN', 'Bulgarian lev (BGN)'), ('CZK', 'Czech koruna (CZK)'), ('DKK', 'Danish krone (DKK)'), ('EEK', 'Estonian kroon (EEK)'), ('GBP', 'Pound sterling (GBP)'), ('HUF', 'Hungarian forint (HUF)'), ('PLN', 'Polish zloty (PLN)'), ('RON', 'Romanian leu (RON)'), ('SEK', 'Swedish krona (SEK)'), ('CHF', 'Swiss franc (CHF)'), ('ISK', 'Icelandic krona (ISK)'), ('NOK', 'Norwegian krone (NOK)'), ('HRK', 'Croatian kuna (HRK)'), ('RUB', 'Russian rouble (RUB)'), ('TRY', 'Turkish lira (TRY)'), ('AUD', 'Australian dollar (AUD)'), ('BRL', 'Brasilian real (BRL)'), ('CAD', 'Canadian dollar (CAD)'), ('CNY', 'Chinese yuan renminbi (CNY)'), ('HKD', 'Hong Kong dollar (HKD)'), ('IDR', 'Indonesian rupiah (IDR)'), ('INR', 'Indian rupee (INR)'), ('KRW', 'South Korean won (KRW)'), ('MXN', 'Mexican peso (MXN)'), ('MYR', 'Malaysian ringgit (MYR)'), ('NZD', 'New Zealand dollar (NZD)'), ('PHP', 'Philippine peso (PHP)'), ('SGD', 'Singapore dollar (SGD)'), ('THB', 'Thai baht (THB)'), ('ZAR', 'South African rand (ZAR)')], max_length=3)),
                ('rate', models.FloatField(max_length=10)),
                ('from_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Currency',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='currency',
            name='user',
            field=models.ManyToManyField(related_name='currencies', through='scraper.UserCurrency', to=settings.AUTH_USER_MODEL),
        ),
    ]
